- completion_time: 1
  content_match: ''
  content_match_regex: false
  conversion_method: none
  creator: admin
  definition: Definition
  delete_spaces_before_matching: false
  description: Start point of a workflow
  device_query: ''
  device_query_property: ip_address
  devices: []
  dict_match: {}
  display_only_failed_nodes: true
  events: []
  impacting: true
  include_device_results: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_devices: ''
  iteration_devices_property: ip_address
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.482457'
  log_level: 1
  mail_recipient: ''
  max_number_of_retries: 100
  max_processes: 5
  maximum_runs: 1
  multiprocessing: false
  name: '[Shared] Start'
  negative_logic: false
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  postprocessing: ''
  postprocessing_mode: always
  preprocessing: ''
  public: true
  reserved: false
  run_method: per_device
  scoped_name: Start
  send_notification: false
  send_notification_method: mail
  shared: true
  skip: false
  skip_query: ''
  skip_value: 'True'
  time_between_retries: 10
  type: swiss_army_knife_service
  update_pools: false
  validation_method: none
  vendor: ''
  waiting_time: 0
- completion_time: 1
  content_match: ''
  content_match_regex: false
  conversion_method: none
  creator: admin
  definition: Definition
  delete_spaces_before_matching: false
  description: End point of a workflow
  device_query: ''
  device_query_property: ip_address
  devices: []
  dict_match: {}
  display_only_failed_nodes: true
  events: []
  impacting: true
  include_device_results: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_devices: ''
  iteration_devices_property: ip_address
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.491375'
  log_level: 1
  mail_recipient: ''
  max_number_of_retries: 100
  max_processes: 5
  maximum_runs: 1
  multiprocessing: false
  name: '[Shared] End'
  negative_logic: false
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  postprocessing: ''
  postprocessing_mode: always
  preprocessing: ''
  public: true
  reserved: false
  run_method: per_device
  scoped_name: End
  send_notification: false
  send_notification_method: mail
  shared: true
  skip: false
  skip_query: ''
  skip_value: 'True'
  time_between_retries: 10
  type: swiss_army_knife_service
  update_pools: false
  validation_method: none
  vendor: ''
  waiting_time: 0
- completion_time: 1
  content_match: ''
  content_match_regex: false
  conversion_method: none
  creator: admin
  definition: Definition
  delete_spaces_before_matching: false
  description: Monitor eNMS cluster
  device_query: ''
  device_query_property: ip_address
  devices: []
  dict_match: {}
  display_only_failed_nodes: true
  events: []
  impacting: true
  include_device_results: true
  include_link_in_summary: true
  initial_payload: {}
  iteration_devices: ''
  iteration_devices_property: ip_address
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2019-06-24 07:19:52.522003'
  log_level: 1
  mail_recipient: ''
  max_number_of_retries: 100
  max_processes: 5
  maximum_runs: 1
  multiprocessing: false
  name: cluster_monitoring
  negative_logic: false
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  postprocessing: ''
  postprocessing_mode: always
  preprocessing: ''
  reserved: false
  run_method: per_device
  scoped_name: cluster_monitoring
  send_notification: false
  send_notification_method: mail
  shared: false
  skip: false
  skip_query: ''
  skip_value: 'True'
  time_between_retries: 10
  type: swiss_army_knife_service
  update_pools: false
  validation_method: none
  vendor: ''
  waiting_time: 0
- completion_time: 1
  content_match: ''
  content_match_regex: false
  conversion_method: none
  creator: admin
  definition: Definition
  delete_spaces_before_matching: false
  description: ''
  device_query: ''
  device_query_property: name
  devices: []
  dict_match: {}
  display_only_failed_nodes: false
  events: []
  impacting: true
  include_device_results: false
  include_link_in_summary: false
  initial_payload: {}
  iteration_devices: ''
  iteration_devices_property: name
  iteration_values: ''
  iteration_variable_name: iteration_value
  last_modified: '2020-03-25 10:28:56.479710'
  log_level: 1
  mail_recipient: ''
  max_number_of_retries: 100
  max_processes: 15
  maximum_runs: 1
  multiprocessing: false
  name: '[Shared] Placeholder'
  negative_logic: false
  notification_header: ''
  number_of_retries: 0
  operating_system: ''
  pools: []
  positions: {}
  postprocessing: ''
  postprocessing_mode: always
  preprocessing: ''
  public: true
  reserved: false
  run_method: per_device
  scoped_name: Placeholder
  send_notification: false
  send_notification_method: mail
  shared: true
  skip: false
  skip_query: ''
  skip_value: 'True'
  time_between_retries: 10
  type: swiss_army_knife_service
  update_pools: false
  validation_method: none
  vendor: ''
  waiting_time: 0
