---
- name: save running-config
  hosts: all
  connection: local

  vars:
    provider:
      host: "{{ inventory_hostname }}" 
      username: "cisco"
      password: "cisco"


  tasks:
    - ios_command:
        provider: "{{ provider }}"
        commands: show running-config
      register: output

    - copy: 
        content: "{{ output.stdout[0] }}"
        dest: "./output.txt"
